name: avi
favicon: null
layout_spectrum: 0.23859
typography_spectrum: 0.08368070749565959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.970256496919319
  lightness: 0.5468806514982134
  saturation: 0.4231851762160659
  rhythmicContrast: 0.9415687303990126
purpose: []
